/**
 * Footer Block 元数据
 */

import type { ComponentMeta } from "~/types/component-meta";

export const meta: ComponentMeta = {
  type: "footer",
  name: "页脚",
  icon: "i-carbon-row-collapse",
  category: "layout",
  description:
    "页脚组件，支持多布局/多主题、品牌信息、协议链接、联系方式、社交媒体、邮件订阅、App 下载",

  singleton: true,
  allowedPosition: "last",

  propsSchema: [
    // --- 布局 ---
    {
      key: "layout",
      label: "布局方式",
      type: "select",
      defaultValue: "standard",
      options: [
        { label: "标准布局", value: "standard" },
        { label: "等列布局", value: "columns" },
        { label: "居中布局", value: "centered" },
        { label: "极简布局", value: "minimal" },
      ],
      group: "layout",
    },
    {
      key: "contentWidth",
      label: "内容宽度",
      type: "select",
      defaultValue: "contained",
      options: [
        { label: "全宽", value: "full" },
        { label: "标准 (1400px)", value: "contained" },
        { label: "窄 (960px)", value: "narrow" },
      ],
      group: "layout",
    },
    // --- 主题 ---
    {
      key: "theme",
      label: "主题",
      type: "select",
      defaultValue: "dark",
      options: [
        { label: "深色", value: "dark" },
        { label: "浅色", value: "light" },
        { label: "透明", value: "transparent" },
        { label: "渐变", value: "gradient" },
      ],
      group: "theme",
    },
    {
      key: "backgroundImage",
      label: "背景图片 URL",
      type: "text",
      placeholder: "https://...",
      group: "theme",
    },
    {
      key: "backgroundOverlay",
      label: "背景遮罩",
      type: "switch",
      defaultValue: true,
      description: "背景图片上叠加半透明深色遮罩",
      group: "theme",
    },
    // --- 边框 ---
    {
      key: "borderTop",
      label: "顶部边框",
      type: "switch",
      defaultValue: true,
      group: "theme",
    },
    {
      key: "borderStyle",
      label: "边框样式",
      type: "select",
      defaultValue: "solid",
      options: [
        { label: "实线", value: "solid" },
        { label: "渐变", value: "gradient" },
        { label: "无", value: "none" },
      ],
      group: "theme",
    },
    // --- 内容开关 ---
    {
      key: "showContact",
      label: "显示联系方式",
      type: "switch",
      defaultValue: true,
      group: "content",
    },
    {
      key: "showSocial",
      label: "显示社交媒体",
      type: "switch",
      defaultValue: true,
      group: "content",
    },
    {
      key: "showProtocol",
      label: "显示协议链接",
      type: "switch",
      defaultValue: true,
      group: "content",
    },
    {
      key: "showCopyright",
      label: "显示版权信息",
      type: "switch",
      defaultValue: true,
      group: "content",
    },
    {
      key: "showPaymentIcons",
      label: "显示物流图标",
      type: "switch",
      defaultValue: true,
      group: "content",
    },
    // --- 品牌 ---
    {
      key: "showBrandLogo",
      label: "显示品牌 Logo",
      type: "switch",
      defaultValue: false,
      group: "brand",
    },
    {
      key: "logoUrl",
      label: "Logo 图片 URL",
      type: "text",
      placeholder: "https://...",
      group: "brand",
    },
    {
      key: "logoSize",
      label: "Logo 尺寸",
      type: "select",
      defaultValue: "medium",
      options: [
        { label: "小", value: "small" },
        { label: "中", value: "medium" },
        { label: "大", value: "large" },
      ],
      group: "brand",
    },
    // --- 社交媒体 ---
    {
      key: "socialStyle",
      label: "社交图标形状",
      type: "select",
      defaultValue: "rounded",
      options: [
        { label: "圆角方形", value: "rounded" },
        { label: "直角方形", value: "square" },
        { label: "圆形", value: "circle" },
        { label: "描边圆形", value: "outline" },
      ],
      group: "social",
    },
    {
      key: "socialSize",
      label: "社交图标尺寸",
      type: "select",
      defaultValue: "medium",
      options: [
        { label: "小", value: "small" },
        { label: "中", value: "medium" },
        { label: "大", value: "large" },
      ],
      group: "social",
    },
    {
      key: "socialPosition",
      label: "社交图标位置",
      type: "select",
      defaultValue: "brand",
      options: [
        { label: "品牌区下方", value: "brand" },
        { label: "底部版权旁", value: "bottom" },
        { label: "独立分区", value: "separate" },
      ],
      group: "social",
    },
    // --- 返回顶部 ---
    {
      key: "showBackToTop",
      label: "返回顶部按钮",
      type: "switch",
      defaultValue: true,
      group: "backtop",
    },
    {
      key: "backToTopMode",
      label: "显示模式",
      type: "select",
      defaultValue: "auto",
      options: [
        { label: "自动 (滚动后显示)", value: "auto" },
        { label: "始终显示", value: "always" },
        { label: "不显示", value: "never" },
      ],
      group: "backtop",
    },
    {
      key: "backToTopStyle",
      label: "按钮样式",
      type: "select",
      defaultValue: "circle",
      options: [
        { label: "圆形", value: "circle" },
        { label: "方形", value: "square" },
        { label: "胶囊", value: "pill" },
        { label: "火箭", value: "rocket" },
      ],
      group: "backtop",
    },
    {
      key: "backToTopPosition",
      label: "按钮位置",
      type: "select",
      defaultValue: "right",
      options: [
        { label: "右下", value: "right" },
        { label: "左下", value: "left" },
        { label: "居中", value: "center" },
      ],
      group: "backtop",
    },
    // --- 动画 ---
    {
      key: "enableAnimations",
      label: "启用动画",
      type: "switch",
      defaultValue: true,
      group: "animation",
    },
    {
      key: "hoverEffect",
      label: "悬停效果",
      type: "select",
      defaultValue: "lift",
      options: [
        { label: "上浮", value: "lift" },
        { label: "发光", value: "glow" },
        { label: "下划线", value: "underline" },
        { label: "无", value: "none" },
      ],
      group: "animation",
    },
    // --- 邮件订阅 ---
    {
      key: "showNewsletter",
      label: "显示邮件订阅",
      type: "switch",
      defaultValue: false,
      group: "newsletter",
    },
    {
      key: "newsletterTitle",
      label: "订阅标题",
      type: "text",
      defaultValue: "订阅我们的新闻",
      placeholder: "订阅标题文字",
      group: "newsletter",
    },
    // --- App 下载 ---
    {
      key: "showAppDownload",
      label: "显示 App 下载",
      type: "switch",
      defaultValue: false,
      group: "app",
    },
    {
      key: "appStoreUrl",
      label: "App Store 链接",
      type: "text",
      placeholder: "https://apps.apple.com/...",
      group: "app",
    },
    {
      key: "playStoreUrl",
      label: "Google Play 链接",
      type: "text",
      placeholder: "https://play.google.com/...",
      group: "app",
    },
  ],

  defaultProps: {
    layout: "standard",
    contentWidth: "contained",
    theme: "dark",
    backgroundOverlay: true,
    borderTop: true,
    borderStyle: "solid",
    showContact: true,
    showSocial: true,
    showProtocol: true,
    showCopyright: true,
    showPaymentIcons: true,
    showBrandLogo: false,
    logoSize: "medium",
    socialStyle: "rounded",
    socialSize: "medium",
    socialPosition: "brand",
    showBackToTop: true,
    backToTopMode: "auto",
    backToTopStyle: "circle",
    backToTopPosition: "right",
    enableAnimations: true,
    hoverEffect: "lift",
    showNewsletter: false,
    newsletterTitle: "订阅我们的新闻",
    showAppDownload: false,
  },

  styleSchema: [
    {
      key: "backgroundColor",
      label: "背景颜色",
      type: "color",
      placeholder: "由主题预设控制",
      group: "background",
    },
    {
      key: "backgroundImage",
      label: "背景图片",
      type: "text",
      placeholder: "url(...)",
      group: "background",
    },
    {
      key: "--footer-text-color",
      label: "文字颜色",
      type: "color",
      placeholder: "由主题预设控制",
      group: "color",
    },
    {
      key: "--footer-link-color",
      label: "链接颜色",
      type: "color",
      placeholder: "由主题预设控制",
      group: "color",
    },
    {
      key: "--footer-social-bg",
      label: "社交图标背景",
      type: "color",
      placeholder: "由主题预设控制",
      group: "color",
    },
    {
      key: "paddingTop",
      label: "上内边距",
      type: "text",
      defaultValue: "48px",
      placeholder: "48px",
      group: "padding",
    },
    {
      key: "paddingBottom",
      label: "下内边距",
      type: "text",
      defaultValue: "24px",
      placeholder: "24px",
      group: "padding",
    },
    {
      key: "paddingLeft",
      label: "左内边距",
      type: "text",
      defaultValue: "24px",
      placeholder: "24px",
      group: "padding",
    },
    {
      key: "paddingRight",
      label: "右内边距",
      type: "text",
      defaultValue: "24px",
      placeholder: "24px",
      group: "padding",
    },
  ],

  eventsSchema: [
    { event: "click", label: "点击", description: "点击页脚时触发" },
  ],

  defaultStyle: {
    base: {
      paddingTop: "48px",
      paddingBottom: "24px",
      paddingLeft: "24px",
      paddingRight: "24px",
    },
    mobile: {
      paddingTop: "32px",
      paddingBottom: "16px",
      paddingLeft: "16px",
      paddingRight: "16px",
    },
  },

  isContainer: false,
  tags: [
    "页脚",
    "footer",
    "版权",
    "联系方式",
    "社交媒体",
    "协议",
    "订阅",
    "下载",
  ],
};
