# 种子调优（空卷首启专用）：缓存区名称必须与主配置引用一致，尺寸给最小安全值
proxy_cache_path /var/cache/nginx/image levels=1:2 keys_zone=IMAGE_CACHE:64m max_size=1g inactive=30d use_temp_path=off;
proxy_cache_path /var/cache/nginx/nuxt levels=1:2 keys_zone=NUXT_CACHE:64m max_size=512m inactive=365d use_temp_path=off;
ssl_certificate_cache max=4096 inactive=10m valid=5m;
ssl_session_cache shared:SSL:10m;
access_log off;
