package cn.v7soft.dao.enums;

public enum DnsSwitchEventType {
    HEALTH_STATUS_CHANGED,
    DNS_SWITCH_SUBMITTED,
    DNS_SWITCH_SUBMIT_FAILED,
    DNS_SWITCH_CONFIRMED,
    DNS_SWITCH_CONFIRM_FAILED,
    DNS_STARTUP_VERIFIED,
    DNS_NO_HEALTHY_TARGET
}
