/**
 * PromoBar Block 元数据
 * 限时促销条 - 促销文案、折扣徽章、价格展示和可选倒计时
 */

import type { ComponentMeta } from '~/types/component-meta'

export const meta: ComponentMeta = {
  type: 'promobar',
  name: '限时促销条',
  icon: 'i-carbon-flash',
  category: 'marketing',
  description: '促销文案 + 折扣徽章 + 价格 + 倒计时，价格可自动读取当前商品',

  propsSchema: [
    {
      key: 'text',
      label: '促销文案',
      type: 'text',
      defaultValue: '限时特惠，售完即止',
      placeholder: '例如：Oferta por tiempo limitado',
      group: 'content',
    },
    {
      key: 'showBadge',
      label: '显示折扣徽章',
      type: 'switch',
      defaultValue: true,
      group: 'content',
    },
    {
      key: 'badgeText',
      label: '徽章文本',
      type: 'text',
      defaultValue: '',
      placeholder: '留空时按商品价格自动计算（如 50% OFF）',
      description: '留空且开启自动价格时，按划线价与现价自动计算折扣百分比',
      group: 'content',
      showIf: 'showBadge === true',
    },
    {
      key: 'showPrice',
      label: '显示价格',
      type: 'switch',
      defaultValue: true,
      group: 'price',
    },
    {
      key: 'autoPrice',
      label: '自动读取商品价格',
      type: 'switch',
      defaultValue: true,
      description: '在商品详情页自动读取当前商品/规格价格；关闭后使用手动填写的价格',
      group: 'price',
      showIf: 'showPrice === true',
    },
    {
      key: 'manualPrice',
      label: '手动现价',
      type: 'text',
      defaultValue: '',
      placeholder: '例如：45,00 €',
      group: 'price',
      showIf: 'autoPrice === false',
    },
    {
      key: 'manualOriginPrice',
      label: '手动划线价',
      type: 'text',
      defaultValue: '',
      placeholder: '例如：90,00 €',
      group: 'price',
      showIf: 'autoPrice === false',
    },
    {
      key: 'originPriceLabel',
      label: '划线价前缀',
      type: 'text',
      defaultValue: 'RRP:',
      placeholder: 'RRP:',
      group: 'price',
    },
    {
      key: 'countdownEnabled',
      label: '启用倒计时',
      type: 'switch',
      defaultValue: false,
      group: 'countdown',
    },
    {
      key: 'countdownMode',
      label: '倒计时模式',
      type: 'select',
      defaultValue: 'cycle',
      options: [
        { label: '循环周期（每 N 小时重置）', value: 'cycle' },
        { label: '固定截止时间', value: 'fixed' },
      ],
      group: 'countdown',
      showIf: 'countdownEnabled === true',
    },
    {
      key: 'countdownHours',
      label: '循环周期（小时）',
      type: 'number',
      defaultValue: 24,
      min: 1,
      max: 720,
      step: 1,
      group: 'countdown',
      showIf: 'countdownMode === cycle',
    },
    {
      key: 'countdownEndTime',
      label: '截止时间',
      type: 'text',
      defaultValue: '',
      placeholder: '例如：2026-12-31 23:59:59',
      group: 'countdown',
      showIf: 'countdownMode === fixed',
    },
    {
      key: 'expiredBehavior',
      label: '到期后行为',
      type: 'select',
      defaultValue: 'zero',
      options: [
        { label: '保留并显示 00:00:00', value: 'zero' },
        { label: '隐藏倒计时', value: 'hide' },
      ],
      group: 'countdown',
      showIf: 'countdownMode === fixed',
    },
  ],

  defaultProps: {
    text: '限时特惠，售完即止',
    showBadge: true,
    badgeText: '',
    showPrice: true,
    autoPrice: true,
    manualPrice: '',
    manualOriginPrice: '',
    originPriceLabel: 'RRP:',
    countdownEnabled: false,
    countdownMode: 'cycle',
    countdownEndTime: '',
    countdownHours: 24,
    expiredBehavior: 'zero',
  },

  styleSchema: [
    { key: '--promo-bg', label: '背景', type: 'color', group: 'background' },
    { key: '--promo-color', label: '文字颜色', type: 'color', defaultValue: '#ffffff', group: 'text' },
    { key: '--promo-text-size', label: '文案字号', type: 'text', placeholder: '15px', group: 'text' },
    { key: '--promo-price-size', label: '现价字号', type: 'text', placeholder: '18px', group: 'text' },
    { key: '--promo-price-color', label: '现价颜色', type: 'color', group: 'text' },
    { key: '--promo-origin-price-color', label: '划线价颜色', type: 'color', group: 'text' },
    { key: '--promo-badge-bg', label: '徽章背景', type: 'color', defaultValue: '#ffffff', group: 'badge' },
    { key: '--promo-badge-color', label: '徽章文字色', type: 'color', defaultValue: '#ef4444', group: 'badge' },
    { key: '--promo-countdown-digit-bg', label: '倒计时数字背景', type: 'color', group: 'countdown' },
    { key: '--promo-countdown-digit-color', label: '倒计时数字颜色', type: 'color', group: 'countdown' },
    {
      key: '--promo-justify',
      label: '对齐方式',
      type: 'select',
      defaultValue: 'center',
      options: [
        { label: '居中', value: 'center' },
        { label: '左对齐', value: 'flex-start' },
        { label: '两端对齐', value: 'space-between' },
      ],
      group: 'layout',
    },
    { key: '--promo-padding', label: '内边距', type: 'text', placeholder: '10px 16px', group: 'layout' },
    { key: '--promo-radius', label: '圆角', type: 'text', placeholder: '0', group: 'layout' },
    { key: '--promo-gap', label: '元素间距', type: 'text', placeholder: '12px', group: 'layout' },
  ],

  defaultStyle: {
    base: {},
  },

  isContainer: false,
  tags: ['促销', '限时', '倒计时', '折扣', 'promo', 'countdown', 'sale', 'discount'],
}
