/**
 * CheckoutPage Block 元数据
 * 收银台页面组件 - 整合收货地址、商品列表、订单汇总和提交按钮
 */

import type { ComponentMeta } from "~/types/component-meta";

export const meta: ComponentMeta = {
  type: "checkoutpage",
  name: "收银台",
  icon: "i-carbon-shopping-cart",
  category: "business",
  description: "收银台页面组件，左侧显示订单汇总（商品+金额），右侧显示收货表单和提交按钮",

  allowedPages: ["checkout"],

  propsSchema: [
    // 布局配置
    {
      key: "layout",
      label: "页面布局",
      type: "select",
      defaultValue: "two-column",
      options: [
        { label: "左右布局", value: "two-column" },
        { label: "单列布局", value: "single-column" },
      ],
      description: "页面整体布局方式，左右布局在移动端自动降级为单列",
      group: "layout",
    },
    // 地址表单配置
    {
      key: "addressLayout",
      label: "表单布局",
      type: "select",
      defaultValue: "single",
      options: [
        { label: "双列布局", value: "double" },
        { label: "单列布局", value: "single" },
      ],
      description: "地址表单字段的排列方式",
      group: "address",
    },
    {
      key: "showEmail",
      label: "显示邮箱",
      type: "switch",
      defaultValue: true,
      description: "是否显示邮箱字段",
      group: "address",
    },
    {
      key: "showNote",
      label: "显示备注",
      type: "switch",
      defaultValue: true,
      description: "是否显示订单备注字段",
      group: "address",
    },
    // 商品列表配置
    {
      key: "showImage",
      label: "显示图片",
      type: "switch",
      defaultValue: true,
      description: "是否显示商品图片",
      group: "items",
    },
    {
      key: "imageSize",
      label: "图片尺寸",
      type: "select",
      defaultValue: "small",
      options: [
        { label: "小", value: "small" },
        { label: "中", value: "medium" },
        { label: "大", value: "large" },
      ],
      description: "商品图片的尺寸大小",
      showIf: "showImage === true",
      group: "items",
    },
    {
      key: "showSpec",
      label: "显示规格",
      type: "switch",
      defaultValue: true,
      description: "是否显示商品规格信息",
      group: "items",
    },
    {
      key: "showQuantity",
      label: "显示数量",
      type: "switch",
      defaultValue: true,
      description: "是否显示商品数量",
      group: "items",
    },
    {
      key: "showPrice",
      label: "显示价格",
      type: "switch",
      defaultValue: true,
      description: "是否显示商品价格",
      group: "items",
    },
    // 订单汇总配置
    {
      key: "summaryLayout",
      label: "汇总样式",
      type: "select",
      defaultValue: "detailed",
      options: [
        { label: "详细", value: "detailed" },
        { label: "紧凑", value: "compact" },
      ],
      description: "订单汇总的显示样式",
      group: "summary",
    },
    {
      key: "showItemCount",
      label: "显示商品数",
      type: "switch",
      defaultValue: false,
      description: "是否显示商品数量统计",
      group: "summary",
    },
    {
      key: "showShipping",
      label: "显示运费",
      type: "switch",
      defaultValue: true,
      description: "是否显示运费信息",
      group: "summary",
    },
    {
      key: "showDiscount",
      label: "显示优惠",
      type: "switch",
      defaultValue: true,
      description: "是否显示优惠金额",
      group: "summary",
    },
    // 提交按钮配置
    {
      key: "submitText",
      label: "按钮文本",
      type: "text",
      defaultValue: "",
      placeholder: "提交订单",
      group: "submit",
    },
    {
      key: "submitLoadingText",
      label: "加载文本",
      type: "text",
      defaultValue: "",
      placeholder: "提交中...",
      group: "submit",
    },
    {
      key: "submitSize",
      label: "按钮尺寸",
      type: "select",
      defaultValue: "large",
      options: [
        { label: "小", value: "small" },
        { label: "中", value: "medium" },
        { label: "大", value: "large" },
      ],
      group: "submit",
    },
    {
      key: "submitFullWidth",
      label: "按钮撑满",
      type: "switch",
      defaultValue: true,
      description: "按钮是否撑满容器宽度",
      group: "submit",
    },
    {
      key: "showSubmitNote",
      label: "显示提示",
      type: "switch",
      defaultValue: true,
      description: "是否显示提交按钮下方的提示文字",
      group: "submit",
    },
    {
      key: "submitNoteText",
      label: "提示文本",
      type: "text",
      defaultValue: "",
      placeholder: "提示文本",
      showIf: "showSubmitNote === true",
      group: "submit",
    },
  ],

  defaultProps: {
    layout: "two-column",
    // 地址表单
    addressLayout: "single",
    showEmail: true,
    showNote: true,
    // 商品列表
    showImage: true,
    imageSize: "small",
    showSpec: true,
    showQuantity: true,
    showPrice: true,
    // 订单汇总
    summaryLayout: "detailed",
    showItemCount: false,
    showShipping: true,
    showDiscount: true,
    // 提交按钮
    submitText: "",
    submitLoadingText: "",
    submitSize: "large",
    submitFullWidth: false,
    showSubmitNote: false,
    submitNoteText: "",
  },

  styleSchema: [
    // 页面布局样式
    {
      key: "--checkout-max-width",
      label: "最大宽度",
      type: "text",
      defaultValue: "1200px",
      placeholder: "1200px",
      group: "layout",
    },
    {
      key: "--checkout-padding",
      label: "页面内边距",
      type: "text",
      defaultValue: "24px 16px",
      placeholder: "24px 16px",
      group: "layout",
    },
    {
      key: "--checkout-gap",
      label: "左右间距",
      type: "text",
      defaultValue: "32px",
      placeholder: "32px",
      group: "layout",
    },
    {
      key: "--checkout-sidebar-width",
      label: "侧边栏宽度",
      type: "text",
      defaultValue: "360px",
      placeholder: "360px",
      group: "layout",
    },
    {
      key: "--checkout-section-gap",
      label: "区块间距",
      type: "text",
      defaultValue: "24px",
      placeholder: "24px",
      group: "layout",
    },
    // 区块样式
    {
      key: "--checkout-section-bg",
      label: "区块背景色",
      type: "color",
      placeholder: "#ffffff",
      group: "section",
    },
    {
      key: "--checkout-section-radius",
      label: "区块圆角",
      type: "text",
      defaultValue: "12px",
      placeholder: "12px",
      group: "section",
    },
    {
      key: "--checkout-section-padding",
      label: "区块内边距",
      type: "text",
      defaultValue: "20px",
      placeholder: "20px",
      group: "section",
    },
    {
      key: "--checkout-section-border",
      label: "区块边框色",
      type: "color",
      placeholder: "#e5e7eb",
      group: "section",
    },
    // 标题样式
    {
      key: "--checkout-title-size",
      label: "标题字号",
      type: "text",
      defaultValue: "16px",
      placeholder: "16px",
      group: "title",
    },
    {
      key: "--checkout-title-weight",
      label: "标题字重",
      type: "select",
      defaultValue: "600",
      options: [
        { label: "正常", value: "400" },
        { label: "中等", value: "500" },
        { label: "粗体", value: "600" },
        { label: "加粗", value: "700" },
      ],
      group: "title",
    },
    {
      key: "--checkout-title-color",
      label: "标题颜色",
      type: "color",
      placeholder: "#1f2937",
      group: "title",
    },
    {
      key: "--checkout-title-margin",
      label: "标题下边距",
      type: "text",
      defaultValue: "16px",
      placeholder: "16px",
      group: "title",
    },
    // 地址表单样式
    {
      key: "--address-form-gap",
      label: "表单字段间距",
      type: "text",
      defaultValue: "16px",
      placeholder: "16px",
      group: "address",
    },
    {
      key: "--address-form-input-radius",
      label: "输入框圆角",
      type: "text",
      defaultValue: "8px",
      placeholder: "8px",
      group: "address",
    },
    // 商品列表样式
    {
      key: "--checkout-items-gap",
      label: "商品间距",
      type: "text",
      defaultValue: "16px",
      placeholder: "16px",
      group: "items",
    },
    {
      key: "--checkout-items-image-radius",
      label: "商品图片圆角",
      type: "text",
      defaultValue: "8px",
      placeholder: "8px",
      group: "items",
    },
    // 订单汇总样式
    {
      key: "--order-summary-row-gap",
      label: "汇总行间距",
      type: "text",
      defaultValue: "12px",
      placeholder: "12px",
      group: "summary",
    },
    {
      key: "--order-summary-total-value-size",
      label: "总计字号",
      type: "text",
      defaultValue: "24px",
      placeholder: "24px",
      group: "summary",
    },
    {
      key: "--checkout-divider-margin",
      label: "分隔线边距",
      type: "text",
      defaultValue: "20px 0",
      placeholder: "20px 0",
      group: "summary",
    },
    // 提交按钮样式
    {
      key: "--submit-btn-radius",
      label: "按钮圆角",
      type: "text",
      defaultValue: "10px",
      placeholder: "10px",
      group: "submit",
    },
    {
      key: "--submit-btn-bg",
      label: "按钮背景色",
      type: "color",
      placeholder: "主题色",
      group: "submit",
    },
    {
      key: "--submit-btn-color",
      label: "按钮文字色",
      type: "color",
      defaultValue: "#ffffff",
      placeholder: "#ffffff",
      group: "submit",
    },
  ],

  defaultStyle: {
    base: {
      "--checkout-max-width": "1200px",
      "--checkout-padding": "24px 16px",
      "--checkout-gap": "32px",
      "--checkout-sidebar-width": "380px",
      "--checkout-section-gap": "24px",
      "--checkout-section-radius": "12px",
      "--checkout-section-padding": "24px",
      "--checkout-title-size": "18px",
      "--checkout-title-weight": "700",
      "--checkout-title-margin": "8px",
      "--checkout-subtitle-margin": "20px",
      "--checkout-divider-margin": "20px 0",
      "--address-form-gap": "16px",
      "--address-form-input-radius": "8px",
      "--checkout-items-gap": "16px",
      "--checkout-items-image-radius": "8px",
      "--order-summary-row-gap": "12px",
      "--order-summary-total-value-size": "24px",
      "--submit-btn-radius": "8px",
      "--submit-btn-color": "#ffffff",
    },
    mobile: {
      "--checkout-padding": "16px 12px",
      "--checkout-section-gap": "16px",
      "--checkout-section-padding": "16px",
      "--checkout-title-size": "16px",
      "--address-form-gap": "12px",
    },
  },

  isContainer: false,
  tags: [
    "收银台",
    "结算",
    "订单",
    "支付",
    "地址",
    "checkout",
    "order",
    "payment",
    "address",
  ],
};
