/**
 * HeroSection Block 元数据
 * H5 风格首页海报组件
 */

import type { ComponentMeta } from '~/types/component-meta'

export const meta: ComponentMeta = {
  type: 'herosection',
  name: '海报横幅',
  icon: 'i-carbon-image-reference',
  category: 'business',
  description: 'H5 风格首页海报组件，支持全屏背景图、多层文字和多种预设样式',

  allowedPages: ['home', 'custom'],

  propsSchema: [
    {
      key: 'preset',
      label: '预设样式',
      type: 'select',
      defaultValue: 'classic',
      options: [
        { label: '经典居中', value: 'classic' },
        { label: '左对齐', value: 'left' },
        { label: '底部居中', value: 'bottom' },
        { label: '无遮罩', value: 'minimal' },
        { label: '深色遮罩', value: 'dark' },
      ],
      description: '选择预设样式，可快速应用不同的布局效果',
    },
    {
      key: 'backgroundImage',
      label: '背景图片',
      type: 'image',
      defaultValue: '/mock/hero-bg.svg',
      description: '海报背景图片，建议尺寸 1920x800 或更大',
    },
    {
      key: 'backgroundColor',
      label: '背景颜色',
      type: 'color',
      defaultValue: '#1a1a1a',
      description: '无背景图时显示的颜色',
    },
    {
      key: 'backgroundPosition',
      label: '背景位置',
      type: 'select',
      defaultValue: 'center',
      options: [
        { label: '居中', value: 'center' },
        { label: '顶部', value: 'top' },
        { label: '底部', value: 'bottom' },
        { label: '左侧', value: 'left' },
        { label: '右侧', value: 'right' },
      ],
      description: '背景图片的对齐位置',
    },
    {
      key: 'eyebrow',
      label: '小标题',
      type: 'text',
      defaultValue: 'Breezy looks made for sunny days.',
      placeholder: '如：限时特惠',
      description: '显示在主标题上方的小字',
    },
    {
      key: 'title',
      label: '主标题',
      type: 'text',
      defaultValue: "LUXETTE'S STYLE",
      placeholder: '如：新品上市',
      description: '海报的主要标题文字',
    },
    {
      key: 'subtitle',
      label: '副标题',
      type: 'textarea',
      defaultValue: '',
      placeholder: '如：探索我们的最新系列产品',
      description: '主标题下方的描述文字',
    },
    {
      key: 'buttonText',
      label: '按钮文字',
      type: 'text',
      defaultValue: 'Buy now',
      placeholder: '如：立即购买',
      description: '行动按钮的文字',
    },
    {
      key: 'buttonLinkType',
      label: '链接类型',
      type: 'select',
      defaultValue: 'home',
      options: [
        { label: '首页', value: 'home' },
        { label: '落地页', value: 'landing' },
        { label: '自定义', value: 'custom' },
      ],
      description: '按钮点击后跳转的目标类型',
    },
    {
      key: 'buttonLink',
      label: '自定义链接',
      type: 'text',
      defaultValue: '',
      placeholder: '如：/products 或 https://example.com',
      description: '自定义跳转链接地址',
      showIf: "buttonLinkType === 'custom'",
    },
    {
      key: 'buttonStyle',
      label: '按钮样式',
      type: 'select',
      defaultValue: 'solid',
      options: [
        { label: '实心', value: 'solid' },
        { label: '描边', value: 'outline' },
        { label: '文字', value: 'text' },
      ],
      description: '按钮的视觉样式',
    },
    {
      key: 'contentAlign',
      label: '水平对齐',
      type: 'select',
      defaultValue: 'center',
      options: [
        { label: '左对齐', value: 'left' },
        { label: '居中', value: 'center' },
        { label: '右对齐', value: 'right' },
      ],
      description: '内容的水平对齐方式',
    },
    {
      key: 'contentPosition',
      label: '垂直位置',
      type: 'select',
      defaultValue: 'center',
      options: [
        { label: '顶部', value: 'top' },
        { label: '居中', value: 'center' },
        { label: '底部', value: 'bottom' },
      ],
      description: '内容的垂直位置',
    },
    {
      key: 'overlayType',
      label: '遮罩类型',
      type: 'select',
      defaultValue: 'gradient',
      options: [
        { label: '无', value: 'none' },
        { label: '纯色', value: 'solid' },
        { label: '渐变', value: 'gradient' },
      ],
      description: '背景遮罩的类型',
    },
    {
      key: 'overlayColor',
      label: '遮罩颜色',
      type: 'color',
      defaultValue: '#000000',
      description: '遮罩层的颜色',
      showIf: "overlayType !== 'none'",
    },
    {
      key: 'overlayOpacity',
      label: '遮罩透明度',
      type: 'slider',
      defaultValue: 30,
      min: 0,
      max: 100,
      step: 5,
      description: '遮罩层的透明度（0-100）',
      showIf: "overlayType !== 'none'",
    },
  ],

  defaultProps: {
    preset: 'classic',
    backgroundImage: '/mock/hero-bg.svg',
    backgroundColor: '#1a1a1a',
    backgroundPosition: 'center',
    eyebrow: 'Breezy looks made for sunny days.',
    title: "LUXETTE'S STYLE",
    subtitle: '',
    buttonText: 'Buy now',
    buttonLinkType: 'home',
    buttonLink: '',
    buttonStyle: 'solid',
    contentAlign: 'center',
    contentPosition: 'center',
    overlayType: 'gradient',
    overlayColor: '#000000',
    overlayOpacity: 30,
  },

  styleSchema: [
    {
      key: 'height',
      label: '高度',
      type: 'text',
      defaultValue: '500px',
      placeholder: '500px 或 100vh',
      group: 'size',
    },
    {
      key: 'minHeight',
      label: '最小高度',
      type: 'text',
      defaultValue: '400px',
      placeholder: '400px',
      group: 'size',
    },
    {
      key: 'maxWidth',
      label: '最大宽度',
      type: 'text',
      defaultValue: '100%',
      placeholder: '100%',
      group: 'size',
    },
    {
      key: '--hero-title-size',
      label: '标题字号',
      type: 'text',
      defaultValue: '42px',
      placeholder: '42px',
      group: 'typography',
    },
    {
      key: '--hero-title-color',
      label: '标题颜色',
      type: 'color',
      defaultValue: '#ffffff',
      group: 'typography',
    },
    {
      key: '--hero-title-weight',
      label: '标题字重',
      type: 'select',
      defaultValue: '600',
      options: [
        { label: '正常 (400)', value: '400' },
        { label: '中等 (500)', value: '500' },
        { label: '半粗 (600)', value: '600' },
        { label: '粗体 (700)', value: '700' },
        { label: '特粗 (800)', value: '800' },
      ],
      group: 'typography',
    },
    {
      key: '--hero-eyebrow-size',
      label: '小标题字号',
      type: 'text',
      defaultValue: '14px',
      placeholder: '14px',
      group: 'typography',
    },
    {
      key: '--hero-eyebrow-color',
      label: '小标题颜色',
      type: 'color',
      defaultValue: 'rgba(255, 255, 255, 0.85)',
      group: 'typography',
    },
    {
      key: '--hero-subtitle-size',
      label: '副标题字号',
      type: 'text',
      defaultValue: '16px',
      placeholder: '16px',
      group: 'typography',
    },
    {
      key: '--hero-subtitle-color',
      label: '副标题颜色',
      type: 'color',
      defaultValue: 'rgba(255, 255, 255, 0.8)',
      group: 'typography',
    },
    {
      key: '--hero-button-bg',
      label: '按钮背景色',
      type: 'color',
      defaultValue: 'rgba(0, 0, 0, 0.7)',
      group: 'button',
    },
    {
      key: '--hero-button-color',
      label: '按钮文字色',
      type: 'color',
      defaultValue: '#ffffff',
      group: 'button',
    },
    {
      key: '--hero-button-radius',
      label: '按钮圆角',
      type: 'text',
      defaultValue: '4px',
      placeholder: '4px',
      group: 'button',
    },
    {
      key: 'marginTop',
      label: '上外边距',
      type: 'text',
      defaultValue: '0',
      placeholder: '0',
      group: 'spacing',
    },
    {
      key: 'marginBottom',
      label: '下外边距',
      type: 'text',
      defaultValue: '0',
      placeholder: '0',
      group: 'spacing',
    },
  ],

  defaultStyle: {
    base: {
      height: '500px',
      minHeight: '400px',
      maxWidth: '100%',
      marginTop: '0',
      marginBottom: '0',
      '--hero-title-size': '42px',
      '--hero-title-color': '#ffffff',
      '--hero-title-weight': '600',
      '--hero-eyebrow-size': '14px',
      '--hero-eyebrow-color': 'rgba(255, 255, 255, 0.85)',
      '--hero-subtitle-size': '16px',
      '--hero-subtitle-color': 'rgba(255, 255, 255, 0.8)',
      '--hero-button-bg': 'rgba(0, 0, 0, 0.7)',
      '--hero-button-color': '#ffffff',
      '--hero-button-radius': '4px',
    },
    mobile: {
      height: '400px',
      minHeight: '300px',
      '--hero-title-size': '28px',
      '--hero-eyebrow-size': '12px',
      '--hero-subtitle-size': '14px',
    },
  },

  isContainer: false,
  tags: ['海报', 'banner', 'hero', '首页', '广告', 'H5', '全屏'],
}
