/**
 * InlineOrderForm Block 元数据
 * 内嵌下单表单 - 在商品详情页内直接完成下单（COD 落地页模式）
 */

import type { ComponentMeta } from "~/types/component-meta";

export const meta: ComponentMeta = {
  type: "inlineorderform",
  name: "内嵌下单表单",
  icon: "i-carbon-purchase",
  category: "business",
  description: "商品页内嵌的完整下单表单：价格、数量、收货地址、支付方式与提交按钮",

  allowedPages: ["product-detail"],
  singleton: true,

  propsSchema: [
    {
      key: "showTitle",
      label: "显示标题",
      type: "switch",
      defaultValue: true,
      group: "title",
    },
    {
      key: "title",
      label: "标题文本",
      type: "text",
      defaultValue: "",
      placeholder: "留空使用多语言默认文案（收货信息）",
      group: "title",
      showIf: "showTitle === true",
    },
    {
      key: "showPrice",
      label: "显示价格行",
      type: "switch",
      defaultValue: true,
      description: "展示当前商品/规格的现价、划线价与折扣徽章",
      group: "price",
    },
    {
      key: "priceLabel",
      label: "价格标签",
      type: "text",
      defaultValue: "",
      placeholder: "例如：* Precio:（留空不显示标签）",
      group: "price",
      showIf: "showPrice === true",
    },
    {
      key: "showQuantity",
      label: "显示数量行",
      type: "switch",
      defaultValue: true,
      description: "与页面上的数量选择器组件状态联动",
      group: "quantity",
    },
    {
      key: "quantityLabel",
      label: "数量标签",
      type: "text",
      defaultValue: "",
      placeholder: "留空使用多语言默认文案（数量）",
      group: "quantity",
      showIf: "showQuantity === true",
    },
    {
      key: "showEmail",
      label: "显示邮箱字段",
      type: "switch",
      defaultValue: true,
      group: "address",
    },
    {
      key: "showNote",
      label: "显示备注字段",
      type: "switch",
      defaultValue: true,
      group: "address",
    },
    {
      key: "addressLayout",
      label: "地址表单布局",
      type: "select",
      defaultValue: "single",
      options: [
        { label: "单列", value: "single" },
        { label: "双列", value: "double" },
      ],
      group: "address",
    },
    {
      key: "showPaymentMethod",
      label: "显示支付方式",
      type: "switch",
      defaultValue: true,
      group: "payment",
    },
    {
      key: "paymentLabel",
      label: "支付方式标签",
      type: "text",
      defaultValue: "",
      placeholder: "留空使用多语言默认文案（支付方式）",
      group: "payment",
      showIf: "showPaymentMethod === true",
    },
    {
      key: "codText",
      label: "货到付款文案",
      type: "text",
      defaultValue: "",
      placeholder: "留空使用多语言默认文案（货到付款）",
      group: "payment",
      showIf: "showPaymentMethod === true",
    },
    {
      key: "showSummary",
      label: "显示订单汇总",
      type: "switch",
      defaultValue: true,
      description: "小计/运费/优惠/合计（金额由后端实时计算）",
      group: "summary",
    },
    {
      key: "showShipping",
      label: "汇总显示运费",
      type: "switch",
      defaultValue: true,
      group: "summary",
      showIf: "showSummary === true",
    },
    {
      key: "showDiscount",
      label: "汇总显示优惠",
      type: "switch",
      defaultValue: true,
      group: "summary",
      showIf: "showSummary === true",
    },
    {
      key: "submitText",
      label: "提交按钮文本",
      type: "text",
      defaultValue: "",
      placeholder: "留空使用多语言默认文案（提交订单）",
      group: "submit",
    },
    {
      key: "submitLoadingText",
      label: "提交中文本",
      type: "text",
      defaultValue: "",
      placeholder: "留空使用多语言默认文案（提交中...）",
      group: "submit",
    },
    {
      key: "showSubmitNote",
      label: "显示条款提示",
      type: "switch",
      defaultValue: true,
      group: "submit",
    },
    {
      key: "submitNoteText",
      label: "条款提示文本",
      type: "text",
      defaultValue: "",
      placeholder: "留空使用多语言默认文案",
      group: "submit",
      showIf: "showSubmitNote === true",
    },
  ],

  defaultProps: {
    showTitle: true,
    title: "",
    showPrice: true,
    priceLabel: "",
    showQuantity: true,
    quantityLabel: "",
    showEmail: true,
    showNote: true,
    addressLayout: "single",
    showPaymentMethod: true,
    paymentLabel: "",
    codText: "",
    showSummary: true,
    showShipping: true,
    showDiscount: true,
    submitText: "",
    submitLoadingText: "",
    showSubmitNote: true,
    submitNoteText: "",
  },

  styleSchema: [
    { key: "--iof-max-width", label: "最大宽度", type: "text", placeholder: "720px", group: "size" },
    { key: "--iof-padding", label: "内边距", type: "text", placeholder: "20px", group: "size" },
    { key: "--iof-gap", label: "区块间距", type: "text", placeholder: "16px", group: "size" },
    { key: "--iof-bg", label: "背景颜色", type: "color", defaultValue: "#ffffff", group: "background" },
    { key: "--iof-border", label: "边框", type: "text", placeholder: "1px solid #e5e7eb", group: "border" },
    { key: "--iof-radius", label: "圆角", type: "text", placeholder: "12px", group: "border" },
    { key: "--iof-title-size", label: "标题字号", type: "text", placeholder: "18px", group: "text" },
    { key: "--iof-title-color", label: "标题颜色", type: "color", group: "text" },
    { key: "--iof-label-color", label: "标签颜色", type: "color", group: "text" },
    { key: "--iof-price-size", label: "现价字号", type: "text", placeholder: "24px", group: "price" },
    { key: "--iof-price-color", label: "现价颜色", type: "color", defaultValue: "#ef4444", group: "price" },
    { key: "--iof-origin-price-color", label: "划线价颜色", type: "color", group: "price" },
    { key: "--iof-badge-bg", label: "折扣徽章背景", type: "color", defaultValue: "#fee2e2", group: "price" },
    { key: "--iof-badge-color", label: "折扣徽章文字色", type: "color", defaultValue: "#ef4444", group: "price" },
    { key: "--submit-btn-bg", label: "提交按钮背景", type: "color", placeholder: "主题色", group: "submit" },
    { key: "--submit-btn-color", label: "提交按钮文字色", type: "color", defaultValue: "#ffffff", group: "submit" },
    { key: "--submit-btn-radius", label: "提交按钮圆角", type: "text", placeholder: "10px", group: "submit" },
  ],

  defaultStyle: {
    base: {},
    mobile: {
      "--iof-padding": "16px",
      "--iof-gap": "12px",
    },
  },

  isContainer: false,
  tags: [
    "下单",
    "表单",
    "落地页",
    "货到付款",
    "订单",
    "order",
    "form",
    "cod",
    "landing",
    "checkout",
  ],
}
