/**
 * OrderResultPage Block 元数据
 * 订单结果页组件 - 显示订单提交成功后的结果信息
 */

import type { ComponentMeta } from "~/types/component-meta";

export const meta: ComponentMeta = {
  type: "orderresultpage",
  name: "订单结果",
  icon: "i-carbon-checkmark-outline",
  category: "business",
  description: "订单结果页组件，显示订单提交成功后的订单信息和状态",

  allowedPages: ["order-result"],

  propsSchema: [
    // 布局配置
    {
      key: "layout",
      label: "页面布局",
      type: "select",
      defaultValue: "centered",
      options: [
        { label: "居中布局", value: "centered" },
        { label: "左对齐", value: "left-aligned" },
      ],
      description: "页面整体布局方式",
      group: "layout",
    },
    // 图标配置
    {
      key: "showIcon",
      label: "显示图标",
      type: "switch",
      defaultValue: true,
      description: "是否显示状态图标",
      group: "icon",
    },
    {
      key: "iconType",
      label: "图标类型",
      type: "select",
      defaultValue: "auto",
      options: [
        { label: "自动", value: "auto" },
        { label: "成功", value: "success" },
        { label: "待处理", value: "pending" },
      ],
      description: "图标类型，自动模式根据支付状态显示",
      showIf: "showIcon === true",
      group: "icon",
    },
    // 显示字段配置
    {
      key: "showOrderId",
      label: "显示订单号",
      type: "switch",
      defaultValue: true,
      description: "是否显示订单号",
      group: "fields",
    },
    {
      key: "showAmount",
      label: "显示金额",
      type: "switch",
      defaultValue: true,
      description: "是否显示订单金额",
      group: "fields",
    },
    {
      key: "showRecipient",
      label: "显示收件人",
      type: "switch",
      defaultValue: true,
      description: "是否显示收件人姓名",
      group: "fields",
    },
    {
      key: "showPhone",
      label: "显示电话",
      type: "switch",
      defaultValue: true,
      description: "是否显示联系电话（已脱敏）",
      group: "fields",
    },
    {
      key: "showEmail",
      label: "显示邮箱",
      type: "switch",
      defaultValue: true,
      description: "是否显示邮箱（已脱敏）",
      group: "fields",
    },
    {
      key: "showAddress",
      label: "显示地址",
      type: "switch",
      defaultValue: true,
      description: "是否显示收货地址（已脱敏）",
      group: "fields",
    },
    {
      key: "showPaymentMethod",
      label: "显示支付方式",
      type: "switch",
      defaultValue: true,
      description: "是否显示支付方式",
      group: "fields",
    },
    {
      key: "showPaymentStatus",
      label: "显示支付状态",
      type: "switch",
      defaultValue: true,
      description: "是否显示支付状态",
      group: "fields",
    },
    {
      key: "showOrderTime",
      label: "显示下单时间",
      type: "switch",
      defaultValue: true,
      description: "是否显示下单时间",
      group: "fields",
    },
    // 文案配置
    {
      key: "successTitle",
      label: "成功标题",
      type: "text",
      defaultValue: "",
      placeholder: "订单提交成功",
      group: "text",
    },
    {
      key: "pendingTitle",
      label: "待处理标题",
      type: "text",
      defaultValue: "",
      placeholder: "订单待支付",
      group: "text",
    },
    {
      key: "successDesc",
      label: "成功描述",
      type: "text",
      defaultValue: "",
      placeholder: "感谢您的购买，我们将尽快处理您的订单。",
      group: "text",
    },
    {
      key: "pendingDesc",
      label: "待处理描述",
      type: "text",
      defaultValue: "",
      placeholder: "请尽快完成支付，以便我们处理您的订单。",
      group: "text",
    },
    // 按钮配置
    {
      key: "showBackButton",
      label: "显示返回按钮",
      type: "switch",
      defaultValue: true,
      description: "是否显示返回首页按钮",
      group: "button",
    },
    {
      key: "backButtonText",
      label: "按钮文本",
      type: "text",
      defaultValue: "",
      placeholder: "返回首页",
      showIf: "showBackButton === true",
      group: "button",
    },
    {
      key: "backButtonLink",
      label: "按钮链接",
      type: "text",
      defaultValue: "/",
      placeholder: "/",
      showIf: "showBackButton === true",
      group: "button",
    },
  ],

  defaultProps: {
    layout: "centered",
    showIcon: true,
    iconType: "auto",
    showOrderId: true,
    showAmount: true,
    showRecipient: true,
    showPhone: true,
    showEmail: true,
    showAddress: true,
    showPaymentMethod: true,
    showPaymentStatus: true,
    showOrderTime: true,
    showBackButton: true,
    successTitle: "",
    pendingTitle: "",
    successDesc: "",
    pendingDesc: "",
    backButtonText: "",
    backButtonLink: "/",
  },

  styleSchema: [
    // 页面布局样式
    {
      key: "--order-result-max-width",
      label: "最大宽度",
      type: "text",
      defaultValue: "520px",
      placeholder: "520px",
      group: "layout",
    },
    {
      key: "--order-result-padding",
      label: "页面内边距",
      type: "text",
      defaultValue: "40px 24px",
      placeholder: "40px 24px",
      group: "layout",
    },
    {
      key: "--order-result-bg",
      label: "页面背景色",
      type: "color",
      placeholder: "#f8fafc",
      group: "layout",
    },
    // 图标样式
    {
      key: "--order-result-icon-size",
      label: "图标大小",
      type: "text",
      defaultValue: "72px",
      placeholder: "72px",
      group: "icon",
    },
    {
      key: "--order-result-success-color",
      label: "成功图标颜色",
      type: "color",
      defaultValue: "#22c55e",
      placeholder: "#22c55e",
      group: "icon",
    },
    {
      key: "--order-result-pending-color",
      label: "待处理图标颜色",
      type: "color",
      defaultValue: "#f59e0b",
      placeholder: "#f59e0b",
      group: "icon",
    },
    // 标题样式
    {
      key: "--order-result-title-size",
      label: "标题字号",
      type: "text",
      defaultValue: "28px",
      placeholder: "28px",
      group: "title",
    },
    {
      key: "--order-result-title-weight",
      label: "标题字重",
      type: "select",
      defaultValue: "700",
      options: [
        { label: "正常", value: "400" },
        { label: "中等", value: "500" },
        { label: "粗体", value: "600" },
        { label: "加粗", value: "700" },
      ],
      group: "title",
    },
    {
      key: "--order-result-title-color",
      label: "标题颜色",
      type: "color",
      placeholder: "#1f2937",
      group: "title",
    },
    // 描述样式
    {
      key: "--order-result-desc-size",
      label: "描述字号",
      type: "text",
      defaultValue: "16px",
      placeholder: "16px",
      group: "desc",
    },
    {
      key: "--order-result-desc-color",
      label: "描述颜色",
      type: "color",
      placeholder: "#6b7280",
      group: "desc",
    },
    // 卡片样式
    {
      key: "--order-result-card-bg",
      label: "卡片背景色",
      type: "color",
      placeholder: "#ffffff",
      group: "card",
    },
    {
      key: "--order-result-card-radius",
      label: "卡片圆角",
      type: "text",
      defaultValue: "12px",
      placeholder: "12px",
      group: "card",
    },
    {
      key: "--order-result-card-padding",
      label: "卡片内边距",
      type: "text",
      defaultValue: "24px",
      placeholder: "24px",
      group: "card",
    },
    {
      key: "--order-result-card-border",
      label: "卡片边框色",
      type: "color",
      placeholder: "#e5e7eb",
      group: "card",
    },
    // 金额样式
    {
      key: "--order-result-amount-size",
      label: "金额字号",
      type: "text",
      defaultValue: "20px",
      placeholder: "20px",
      group: "amount",
    },
    {
      key: "--order-result-amount-color",
      label: "金额颜色",
      type: "color",
      placeholder: "主题色",
      group: "amount",
    },
    // 按钮样式
    {
      key: "--order-result-btn-bg",
      label: "按钮背景色",
      type: "color",
      placeholder: "主题色",
      group: "button",
    },
    {
      key: "--order-result-btn-color",
      label: "按钮文字色",
      type: "color",
      defaultValue: "#ffffff",
      placeholder: "#ffffff",
      group: "button",
    },
    {
      key: "--order-result-btn-radius",
      label: "按钮圆角",
      type: "text",
      defaultValue: "8px",
      placeholder: "8px",
      group: "button",
    },
    {
      key: "--order-result-btn-padding",
      label: "按钮内边距",
      type: "text",
      defaultValue: "12px 32px",
      placeholder: "12px 32px",
      group: "button",
    },
  ],

  defaultStyle: {
    base: {
      "--order-result-max-width": "520px",
      "--order-result-padding": "40px 24px",
      "--order-result-icon-size": "72px",
      "--order-result-icon-margin": "24px",
      "--order-result-success-color": "#22c55e",
      "--order-result-pending-color": "#f59e0b",
      "--order-result-title-size": "28px",
      "--order-result-title-weight": "700",
      "--order-result-title-margin": "12px",
      "--order-result-desc-size": "16px",
      "--order-result-desc-margin": "32px",
      "--order-result-card-radius": "12px",
      "--order-result-card-padding": "24px",
      "--order-result-card-margin": "32px",
      "--order-result-row-padding": "12px 0",
      "--order-result-label-size": "14px",
      "--order-result-value-size": "14px",
      "--order-result-amount-size": "20px",
      "--order-result-btn-radius": "8px",
      "--order-result-btn-padding": "12px 32px",
      "--order-result-btn-size": "15px",
      "--order-result-btn-color": "#ffffff",
    },
    mobile: {
      "--order-result-padding": "24px 16px",
      "--order-result-icon-size": "56px",
      "--order-result-title-size": "22px",
      "--order-result-card-padding": "16px",
    },
  },

  isContainer: false,
  tags: [
    "订单结果",
    "订单成功",
    "支付结果",
    "order",
    "result",
    "success",
    "payment",
  ],
};
